# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name_in_sources', models.CharField(max_length=250)),
                ('titles', models.TextField()),
                ('life_dates', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('family_relationship', models.TextField()),
                ('others', models.TextField()),
                ('sources', models.TextField()),
                ('literature', models.TextField()),
                ('author', models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
