# Generated by Django 2.0.3 on 2018-04-10 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0002_remove_historynote_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historynote',
            name='author',
            field=models.ForeignKey(default='hello', on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
