# Generated by Django 2.0.3 on 2018-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0004_auto_20180410_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='historynote',
            name='author_before',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
