# Generated by Django 2.0.3 on 2018-04-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0007_auto_20180411_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='historynote',
            name='article_name',
            field=models.TextField(null=True),
        ),
    ]
