# Generated by Django 2.0.3 on 2018-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0008_historynote_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historynote',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historynote',
            name='family_relationship',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historynote',
            name='life_dates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historynote',
            name='literature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historynote',
            name='name_in_sources',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historynote',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historynote',
            name='sources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historynote',
            name='titles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
