# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0009_auto_20180411_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historynote',
            name='author',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
