# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0010_auto_20180411_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historynote',
            name='title',
        ),
    ]
