# Generated by Django 2.0.3 on 2018-05-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0011_auto_20180425_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='historynote',
            name='note_type',
            field=models.SmallIntegerField(choices=[(1, 'Грамота'), (2, 'Летопись')], default=1),
        ),
    ]
