# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0011_remove_historynote_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historynote',
            name='author_before',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
