# Generated by Django 2.0.3 on 2018-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0012_historynote_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historynote',
            name='note_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
