# Generated by Django 2.0.3 on 2018-05-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0013_auto_20180514_2131'),
        ('testsite', '0012_auto_20180423_2136'),
    ]

    operations = [
    ]
